version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  smart-brewer:
    container_name: smart-brewer
    build: .
    ports:
      - '3000:3000' # HTTP
    links:
      - mongo
    depends_on:
      - mongo
